name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@v1.14.1

    - name: Install Dioxus CLI
      run: cargo binstall -y dioxus-cli --version 0.7.0-alpha.3
      
    - name: Build
      run: dx bundle --platform web -r

    - name: Upload Artifacts
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: ./target/dx/world-ranks/release/web/public
